In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:100% !important;}
div.CodeMirror {font-family:Consolas; font-size:10pt;}
div.output {font-size:10pt}
div.input {font-family:Consolas; font-size:10pt;}
div.prompt {min-width:70px;}
</style>
"""))

In [2]:
import numpy as np 
import tensorflow.keras.utils as utils
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation

# 데이터 셋 생성 

In [3]:
# 데이터 불러오기 
dataset = np.loadtxt('data/pima-indians-diabetes.csv', delimiter=',')
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [4]:
dataset.shape

(768, 9)

In [5]:
# 데이터 분리 

# 학습데이터(훈련데이터)
x_train = dataset[:700, :8]
y_train = dataset[:700, 8]

# 테스트데이터 
x_test = dataset[700: , :8]
y_test = dataset[700: , 8]

In [6]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((700, 8), (700,), (68, 8), (68,))

# 모델 구성하기

In [7]:
model = Sequential()

model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# 학습과정 설정

In [8]:
model.compile(loss='binary_crossentropy', 
              optimizer='adam',
              metrics=['accuracy'])

# 학습시키기

In [9]:
hist = model.fit(x_train, y_train, epochs=1500,
                 batch_size=64, verbose=0)

# 모델 평가

In [11]:
score = model.evaluate(x_test, y_test)

3/3 [==============================] - 0s 2ms/step - loss: 0.6613 - accuracy: 0.7500


In [12]:
print('loss: %s\n, accuracy: %.2f' % (score[0], score[1]))

loss: 0.6613146066665649
, accuracy: 0.75


In [13]:
x_train[0]

array([  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
        50.   ])

In [15]:
model.predict(np.array([[6., 148., 72., 35., 0., 33.6, 0.627, 50.]]))

array([[0.7357959]], dtype=float32)